name: Build Docker Images

on:
  push:
    branches:
      - 'test'
  pull_request:
  workflow_dispatch:

jobs:
  build-api:
    name: Build API Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      # Only login if we're on the test branch
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/test'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          # Push only if we're on the test branch
          push: ${{ github.ref == 'refs/heads/test' }}
          # Load if we're not pushing (i.e., on PR)
          load: ${{ github.ref != 'refs/heads/test' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/firecrawl:${{ github.ref == 'refs/heads/test' && 'latest' || format('pr-{0}', github.event.number) }}
          build-args: |
            PORT=8080

  build-puppeteer:
    name: Build Puppeteer Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      # Only login if we're on the test branch
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/test'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/puppeteer-service-ts/Dockerfile
          # Push only if we're on the test branch
          push: ${{ github.ref == 'refs/heads/test' }}
          # Load if we're not pushing (i.e., on PR)
          load: ${{ github.ref != 'refs/heads/test' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/puppeteer-service-ts:${{ github.ref == 'refs/heads/test' && 'latest' || format('pr-{0}', github.event.number) }}
          build-args: |
            PORT=3000